"""Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms."""


evenTotal = 0
numOne = 1
numTwo = 2
while numOne < 4000000:
    numOne, numTwo = numTwo, numOne + numTwo
    if numOne % 2 == 0:
        evenTotal += numOne
print(evenTotal)
    
